services:
  db-oracle:
    image: db-oracle
    container_name: db-oracle
    hostname: db-oracle  
    ports:
     - "1521:1521"
    shm_size: 2g
    environment:
     - ORACLE_DISABLE_ASYNCH_IO=true
