services:
  postgres:
    image: postgres:17
    container_name: postgrestest
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 123456!
      POSTGRES_DB: data_test
    ports:
      - "5432:5432"
    volumes:
      - ./generate_service_postgresql_test_suite.sql:/docker-entrypoint-initdb.d/01-generate_service_postgresql_test_suite.sql:ro

