services:
  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    restart: always
    command: --log-bin-trust-function-creators=1
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: generate_service_test
      MARIADB_USER: sa
      MARIADB_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./generate_service_mariadb_test_suite.sql:/docker-entrypoint-initdb.d/01-generate_service_mariadb_test_suite.sql:ro
      
