services:
  sql-server:
    image: sql-server
    container_name: sql-server
    hostname: sql-server
    ports:
     - "1433:1433"
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=123456



