SET DEFINE OFF;
SET SQLBLANKLINES ON;

-- Base Oracle 11g test schema for Generate Service.
-- This first stage only creates tables, sequences, seed data and SQL object types.

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE GS_BOOLEAN_TAB FORCE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE GS_INTEGER_TAB FORCE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE GS_TIMESTAMP_TAB FORCE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE GS_DATE_TAB FORCE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE GS_VARCHAR2_TAB FORCE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE GS_NUMBER_TAB FORCE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE GS_PERSONA_DETALLE_TAB FORCE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE GS_PERSONA_DETALLE_OBJ FORCE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE GS_HIJO_TAB FORCE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE GS_HIJO_OBJ FORCE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE GS_DIRECCION_OBJ FORCE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE GS_PERSONA_TAB FORCE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TYPE GS_PERSONA_OBJ FORCE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4043 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE GS_HIJO_DIRECCION CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE GS_HIJO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE GS_PERSONA_DIRECCION CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE GS_PERSONA CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE GS_HIJO_DIRECCION_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE GS_HIJO_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE GS_PERSONA_DIRECCION_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE GS_PERSONA_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

CREATE TABLE GS_PERSONA
(
    ID_PERSONA       NUMBER(10) NOT NULL,
    NOMBRE           VARCHAR2(100) NOT NULL,
    APELLIDO         VARCHAR2(100) NOT NULL,
    EDAD             NUMBER(10) NULL,
    EMAIL            VARCHAR2(150) NULL,
    FECHA_NACIMIENTO DATE NULL,
    ACTIVO           NUMBER(1) DEFAULT 1 NOT NULL,
    FECHA_REGISTRO   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_GS_PERSONA PRIMARY KEY (ID_PERSONA),
    CONSTRAINT CK_GS_PERSONA_ACTIVO CHECK (ACTIVO IN (0, 1))
);

CREATE SEQUENCE GS_PERSONA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER BI_GS_PERSONA
BEFORE INSERT ON GS_PERSONA
FOR EACH ROW
BEGIN
    IF :NEW.ID_PERSONA IS NULL THEN
        SELECT GS_PERSONA_SEQ.NEXTVAL
          INTO :NEW.ID_PERSONA
          FROM DUAL;
    END IF;
END;
/

CREATE TABLE GS_PERSONA_DIRECCION
(
    ID_DIRECCION NUMBER(10) NOT NULL,
    ID_PERSONA   NUMBER(10) NOT NULL,
    PAIS         VARCHAR2(100) NOT NULL,
    CIUDAD       VARCHAR2(100) NOT NULL,
    TELEFONO     VARCHAR2(30) NULL,

    CONSTRAINT PK_GS_PERSONA_DIRECCION PRIMARY KEY (ID_DIRECCION),
    CONSTRAINT FK_GS_PDIR_PERSONA
        FOREIGN KEY (ID_PERSONA) REFERENCES GS_PERSONA(ID_PERSONA)
        ON DELETE CASCADE,
    CONSTRAINT UK_GS_PDIR_PERSONA UNIQUE (ID_PERSONA)
);

CREATE SEQUENCE GS_PERSONA_DIRECCION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER BI_GS_PERSONA_DIRECCION
BEFORE INSERT ON GS_PERSONA_DIRECCION
FOR EACH ROW
BEGIN
    IF :NEW.ID_DIRECCION IS NULL THEN
        SELECT GS_PERSONA_DIRECCION_SEQ.NEXTVAL
          INTO :NEW.ID_DIRECCION
          FROM DUAL;
    END IF;
END;
/

CREATE TABLE GS_HIJO
(
    ID_HIJO          NUMBER(10) NOT NULL,
    ID_PERSONA       NUMBER(10) NOT NULL,
    NOMBRE           VARCHAR2(100) NOT NULL,
    APELLIDO         VARCHAR2(100) NOT NULL,
    FECHA_NACIMIENTO DATE NULL,

    CONSTRAINT PK_GS_HIJO PRIMARY KEY (ID_HIJO),
    CONSTRAINT FK_GS_HIJO_PERSONA
        FOREIGN KEY (ID_PERSONA) REFERENCES GS_PERSONA(ID_PERSONA)
        ON DELETE CASCADE
);

CREATE SEQUENCE GS_HIJO_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER BI_GS_HIJO
BEFORE INSERT ON GS_HIJO
FOR EACH ROW
BEGIN
    IF :NEW.ID_HIJO IS NULL THEN
        SELECT GS_HIJO_SEQ.NEXTVAL
          INTO :NEW.ID_HIJO
          FROM DUAL;
    END IF;
END;
/

CREATE TABLE GS_HIJO_DIRECCION
(
    ID_DIRECCION NUMBER(10) NOT NULL,
    ID_HIJO      NUMBER(10) NOT NULL,
    PAIS         VARCHAR2(100) NOT NULL,
    CIUDAD       VARCHAR2(100) NOT NULL,
    TELEFONO     VARCHAR2(30) NULL,

    CONSTRAINT PK_GS_HIJO_DIRECCION PRIMARY KEY (ID_DIRECCION),
    CONSTRAINT FK_GS_HIJO_DIRECCION_HIJO
        FOREIGN KEY (ID_HIJO) REFERENCES GS_HIJO(ID_HIJO)
        ON DELETE CASCADE,
    CONSTRAINT UK_GS_HIJO_DIRECCION_HIJO UNIQUE (ID_HIJO)
);

CREATE SEQUENCE GS_HIJO_DIRECCION_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE OR REPLACE TRIGGER BI_GS_HIJO_DIRECCION
BEFORE INSERT ON GS_HIJO_DIRECCION
FOR EACH ROW
BEGIN
    IF :NEW.ID_DIRECCION IS NULL THEN
        SELECT GS_HIJO_DIRECCION_SEQ.NEXTVAL
          INTO :NEW.ID_DIRECCION
          FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TYPE GS_PERSONA_OBJ AS OBJECT
(
    ID_PERSONA       NUMBER(10),
    NOMBRE           VARCHAR2(100),
    APELLIDO         VARCHAR2(100),
    EDAD             NUMBER(10),
    EMAIL            VARCHAR2(150),
    FECHA_NACIMIENTO DATE,
    ACTIVO           NUMBER(1),
    FECHA_REGISTRO   TIMESTAMP
);
/

CREATE OR REPLACE TYPE GS_PERSONA_TAB AS TABLE OF GS_PERSONA_OBJ;
/

CREATE OR REPLACE TYPE GS_DIRECCION_OBJ AS OBJECT
(
    PAIS     VARCHAR2(100),
    CIUDAD   VARCHAR2(100),
    TELEFONO VARCHAR2(30)
);
/

CREATE OR REPLACE TYPE GS_HIJO_OBJ AS OBJECT
(
    NOMBRE           VARCHAR2(100),
    APELLIDO         VARCHAR2(100),
    FECHA_NACIMIENTO DATE,
    DIRECCION        GS_DIRECCION_OBJ
);
/

CREATE OR REPLACE TYPE GS_HIJO_TAB AS TABLE OF GS_HIJO_OBJ;
/

CREATE OR REPLACE TYPE GS_PERSONA_DETALLE_OBJ AS OBJECT
(
    ID_PERSONA       NUMBER(10),
    NOMBRE           VARCHAR2(100),
    APELLIDO         VARCHAR2(100),
    EDAD             NUMBER(10),
    EMAIL            VARCHAR2(150),
    FECHA_NACIMIENTO DATE,
    ACTIVO           NUMBER(1),
    FECHA_REGISTRO   TIMESTAMP,
    DIRECCION        GS_DIRECCION_OBJ,
    HIJOS            GS_HIJO_TAB
);
/

CREATE OR REPLACE TYPE GS_PERSONA_DETALLE_TAB AS TABLE OF GS_PERSONA_DETALLE_OBJ;
/

CREATE OR REPLACE TYPE GS_NUMBER_TAB AS TABLE OF NUMBER;
/

CREATE OR REPLACE TYPE GS_INTEGER_TAB AS TABLE OF NUMBER(10);
/

CREATE OR REPLACE TYPE GS_BOOLEAN_TAB AS TABLE OF NUMBER(1);
/

CREATE OR REPLACE TYPE GS_VARCHAR2_TAB AS TABLE OF VARCHAR2(100);
/

CREATE OR REPLACE TYPE GS_DATE_TAB AS TABLE OF DATE;
/

CREATE OR REPLACE TYPE GS_TIMESTAMP_TAB AS TABLE OF TIMESTAMP;
/

INSERT INTO GS_PERSONA
(
    NOMBRE,
    APELLIDO,
    EDAD,
    EMAIL,
    FECHA_NACIMIENTO,
    ACTIVO
)
VALUES
(
    'Alejandro',
    'Mendoza',
    35,
    'alejandro.mendoza@test.com',
    DATE '1991-02-18',
    1
);

INSERT INTO GS_PERSONA
(
    NOMBRE,
    APELLIDO,
    EDAD,
    EMAIL,
    FECHA_NACIMIENTO,
    ACTIVO
)
VALUES
(
    'Carlos',
    'Navarro',
    44,
    'carlos.navarro@test.com',
    DATE '1982-07-11',
    1
);

INSERT INTO GS_PERSONA
(
    NOMBRE,
    APELLIDO,
    EDAD,
    EMAIL,
    FECHA_NACIMIENTO,
    ACTIVO
)
VALUES
(
    'Sofia',
    'Castillo',
    26,
    'sofia.castillo@test.com',
    DATE '2000-01-29',
    0
);

INSERT INTO GS_PERSONA
(
    NOMBRE,
    APELLIDO,
    EDAD,
    EMAIL,
    FECHA_NACIMIENTO,
    ACTIVO
)
VALUES
(
    'Ricardo',
    'Vega',
    38,
    'ricardo.vega@test.com',
    DATE '1988-11-05',
    1
);

INSERT INTO GS_PERSONA
(
    NOMBRE,
    APELLIDO,
    EDAD,
    EMAIL,
    FECHA_NACIMIENTO,
    ACTIVO
)
VALUES
(
    'Gabriela',
    'Torres',
    29,
    'gabriela.torres@test.com',
    DATE '1997-06-22',
    0
);

INSERT INTO GS_PERSONA_DIRECCION
(
    ID_PERSONA,
    PAIS,
    CIUDAD,
    TELEFONO
)
VALUES
(
    1,
    'Colombia',
    'Bogota',
    '3001002000'
);

INSERT INTO GS_PERSONA_DIRECCION
(
    ID_PERSONA,
    PAIS,
    CIUDAD,
    TELEFONO
)
VALUES
(
    2,
    'Mexico',
    'Ciudad de Mexico',
    '3001002001'
);

INSERT INTO GS_PERSONA_DIRECCION
(
    ID_PERSONA,
    PAIS,
    CIUDAD,
    TELEFONO
)
VALUES
(
    3,
    'Peru',
    'Lima',
    '3001002002'
);

INSERT INTO GS_PERSONA_DIRECCION
(
    ID_PERSONA,
    PAIS,
    CIUDAD,
    TELEFONO
)
VALUES
(
    4,
    'Chile',
    'Santiago',
    '3001002003'
);

INSERT INTO GS_PERSONA_DIRECCION
(
    ID_PERSONA,
    PAIS,
    CIUDAD,
    TELEFONO
)
VALUES
(
    5,
    'Argentina',
    'Buenos Aires',
    '3001002004'
);

INSERT INTO GS_HIJO
(
    ID_PERSONA,
    NOMBRE,
    APELLIDO,
    FECHA_NACIMIENTO
)
VALUES
(
    1,
    'Valentina',
    'Mendoza',
    DATE '2015-03-08'
);

INSERT INTO GS_HIJO
(
    ID_PERSONA,
    NOMBRE,
    APELLIDO,
    FECHA_NACIMIENTO
)
VALUES
(
    1,
    'Mateo',
    'Mendoza',
    DATE '2018-09-14'
);

INSERT INTO GS_HIJO
(
    ID_PERSONA,
    NOMBRE,
    APELLIDO,
    FECHA_NACIMIENTO
)
VALUES
(
    2,
    'Emilia',
    'Navarro',
    DATE '2012-12-01'
);

INSERT INTO GS_HIJO
(
    ID_PERSONA,
    NOMBRE,
    APELLIDO,
    FECHA_NACIMIENTO
)
VALUES
(
    4,
    'Lucas',
    'Vega',
    DATE '2016-05-20'
);

INSERT INTO GS_HIJO
(
    ID_PERSONA,
    NOMBRE,
    APELLIDO,
    FECHA_NACIMIENTO
)
VALUES
(
    4,
    'Lucia',
    'Vega',
    DATE '2019-10-03'
);

INSERT INTO GS_HIJO
(
    ID_PERSONA,
    NOMBRE,
    APELLIDO,
    FECHA_NACIMIENTO
)
VALUES
(
    5,
    'Daniela',
    'Torres',
    DATE '2020-01-17'
);

INSERT INTO GS_HIJO_DIRECCION
(
    ID_HIJO,
    PAIS,
    CIUDAD,
    TELEFONO
)
VALUES
(
    1,
    'Colombia',
    'Bogota',
    '3002003001'
);

INSERT INTO GS_HIJO_DIRECCION
(
    ID_HIJO,
    PAIS,
    CIUDAD,
    TELEFONO
)
VALUES
(
    2,
    'Colombia',
    'Medellin',
    '3002003002'
);

INSERT INTO GS_HIJO_DIRECCION
(
    ID_HIJO,
    PAIS,
    CIUDAD,
    TELEFONO
)
VALUES
(
    3,
    'Mexico',
    'Guadalajara',
    '3002003003'
);

INSERT INTO GS_HIJO_DIRECCION
(
    ID_HIJO,
    PAIS,
    CIUDAD,
    TELEFONO
)
VALUES
(
    4,
    'Chile',
    'Valparaiso',
    '3002003004'
);

INSERT INTO GS_HIJO_DIRECCION
(
    ID_HIJO,
    PAIS,
    CIUDAD,
    TELEFONO
)
VALUES
(
    5,
    'Chile',
    'Santiago',
    '3002003005'
);

INSERT INTO GS_HIJO_DIRECCION
(
    ID_HIJO,
    PAIS,
    CIUDAD,
    TELEFONO
)
VALUES
(
    6,
    'Argentina',
    'Cordoba',
    '3002003006'
);

COMMIT;

CREATE OR REPLACE PROCEDURE GS_SP_GET_PERSONA
(
    P_ID_PERSONA IN NUMBER,
    P_PERSONA    OUT GS_PERSONA_OBJ
)
AS
BEGIN
    SELECT GS_PERSONA_OBJ
    (
        P.ID_PERSONA,
        P.NOMBRE,
        P.APELLIDO,
        P.EDAD,
        P.EMAIL,
        P.FECHA_NACIMIENTO,
        P.ACTIVO,
        P.FECHA_REGISTRO
    )
      INTO P_PERSONA
      FROM GS_PERSONA P
     WHERE P.ID_PERSONA = P_ID_PERSONA;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_PERSONA := NULL;
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_GET_PERSONAS
(
    P_PERSONAS OUT GS_PERSONA_TAB
)
AS
BEGIN
    SELECT GS_PERSONA_OBJ
    (
        P.ID_PERSONA,
        P.NOMBRE,
        P.APELLIDO,
        P.EDAD,
        P.EMAIL,
        P.FECHA_NACIMIENTO,
        P.ACTIVO,
        P.FECHA_REGISTRO
    )
      BULK COLLECT INTO P_PERSONAS
      FROM GS_PERSONA P
     ORDER BY P.ID_PERSONA;
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_INSERT_PERSONA
(
    P_PERSONA    IN GS_PERSONA_OBJ,
    P_ID_PERSONA OUT NUMBER
)
AS
BEGIN
    IF P_PERSONA IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'P_PERSONA no puede ser null');
    END IF;

    INSERT INTO GS_PERSONA
    (
        NOMBRE,
        APELLIDO,
        EDAD,
        EMAIL,
        FECHA_NACIMIENTO,
        ACTIVO
    )
    VALUES
    (
        P_PERSONA.NOMBRE,
        P_PERSONA.APELLIDO,
        P_PERSONA.EDAD,
        P_PERSONA.EMAIL,
        P_PERSONA.FECHA_NACIMIENTO,
        NVL(P_PERSONA.ACTIVO, 1)
    )
    RETURNING ID_PERSONA INTO P_ID_PERSONA;
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_UPDATE_PERSONA
(
    P_PERSONA     IN GS_PERSONA_OBJ,
    P_ACTUALIZADO OUT NUMBER
)
AS
BEGIN
    IF P_PERSONA IS NULL THEN
        P_ACTUALIZADO := 0;
        RETURN;
    END IF;

    UPDATE GS_PERSONA
       SET NOMBRE = P_PERSONA.NOMBRE,
           APELLIDO = P_PERSONA.APELLIDO,
           EDAD = P_PERSONA.EDAD,
           EMAIL = P_PERSONA.EMAIL,
           FECHA_NACIMIENTO = P_PERSONA.FECHA_NACIMIENTO,
           ACTIVO = NVL(P_PERSONA.ACTIVO, 1)
     WHERE ID_PERSONA = P_PERSONA.ID_PERSONA;

    P_ACTUALIZADO := CASE WHEN SQL%ROWCOUNT > 0 THEN 1 ELSE 0 END;
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_DELETE_PERSONA
(
    P_ID_PERSONA IN NUMBER,
    P_ELIMINADO  OUT NUMBER
)
AS
BEGIN
    DELETE FROM GS_PERSONA
     WHERE ID_PERSONA = P_ID_PERSONA;

    P_ELIMINADO := CASE WHEN SQL%ROWCOUNT > 0 THEN 1 ELSE 0 END;
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_GET_PERSONA_DETALLE
(
    P_ID_PERSONA IN NUMBER,
    P_PERSONA    OUT GS_PERSONA_DETALLE_OBJ
)
AS
BEGIN
    SELECT GS_PERSONA_DETALLE_OBJ
    (
        P.ID_PERSONA,
        P.NOMBRE,
        P.APELLIDO,
        P.EDAD,
        P.EMAIL,
        P.FECHA_NACIMIENTO,
        P.ACTIVO,
        P.FECHA_REGISTRO,
        (
            SELECT GS_DIRECCION_OBJ
            (
                D.PAIS,
                D.CIUDAD,
                D.TELEFONO
            )
              FROM GS_PERSONA_DIRECCION D
             WHERE D.ID_PERSONA = P.ID_PERSONA
        ),
        CAST
        (
            MULTISET
            (
                SELECT GS_HIJO_OBJ
                (
                    H.NOMBRE,
                    H.APELLIDO,
                    H.FECHA_NACIMIENTO,
                    (
                        SELECT GS_DIRECCION_OBJ
                        (
                            HD.PAIS,
                            HD.CIUDAD,
                            HD.TELEFONO
                        )
                          FROM GS_HIJO_DIRECCION HD
                         WHERE HD.ID_HIJO = H.ID_HIJO
                    )
                )
                  FROM GS_HIJO H
                 WHERE H.ID_PERSONA = P.ID_PERSONA
            )
            AS GS_HIJO_TAB
        )
    )
      INTO P_PERSONA
      FROM GS_PERSONA P
     WHERE P.ID_PERSONA = P_ID_PERSONA;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_PERSONA := NULL;
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_GET_PERSONAS_DETALLE
(
    P_PERSONAS OUT GS_PERSONA_DETALLE_TAB
)
AS
BEGIN
    SELECT GS_PERSONA_DETALLE_OBJ
    (
        P.ID_PERSONA,
        P.NOMBRE,
        P.APELLIDO,
        P.EDAD,
        P.EMAIL,
        P.FECHA_NACIMIENTO,
        P.ACTIVO,
        P.FECHA_REGISTRO,
        (
            SELECT GS_DIRECCION_OBJ
            (
                D.PAIS,
                D.CIUDAD,
                D.TELEFONO
            )
              FROM GS_PERSONA_DIRECCION D
             WHERE D.ID_PERSONA = P.ID_PERSONA
        ),
        CAST
        (
            MULTISET
            (
                SELECT GS_HIJO_OBJ
                (
                    H.NOMBRE,
                    H.APELLIDO,
                    H.FECHA_NACIMIENTO,
                    (
                        SELECT GS_DIRECCION_OBJ
                        (
                            HD.PAIS,
                            HD.CIUDAD,
                            HD.TELEFONO
                        )
                          FROM GS_HIJO_DIRECCION HD
                         WHERE HD.ID_HIJO = H.ID_HIJO
                    )
                )
                  FROM GS_HIJO H
                 WHERE H.ID_PERSONA = P.ID_PERSONA
            )
            AS GS_HIJO_TAB
        )
    )
      BULK COLLECT INTO P_PERSONAS
      FROM GS_PERSONA P
     ORDER BY P.ID_PERSONA;
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_GET_PERSONAS_CURSOR
(
    P_PERSONAS OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_PERSONAS FOR
        SELECT P.ID_PERSONA,
               P.NOMBRE,
               P.APELLIDO,
               P.EDAD,
               P.EMAIL,
               P.FECHA_NACIMIENTO,
               P.ACTIVO,
               P.FECHA_REGISTRO
          FROM GS_PERSONA P
         ORDER BY P.ID_PERSONA;
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_COUNT_PERSONAS_CURSOR
(
    P_PERSONAS IN SYS_REFCURSOR,
    P_TOTAL    OUT NUMBER
)
AS
    V_ID_PERSONA       NUMBER;
    V_NOMBRE           VARCHAR2(100);
    V_APELLIDO         VARCHAR2(100);
    V_EDAD             NUMBER;
    V_EMAIL            VARCHAR2(150);
    V_FECHA_NACIMIENTO DATE;
    V_ACTIVO           NUMBER;
    V_FECHA_REGISTRO   TIMESTAMP;
BEGIN
    P_TOTAL := 0;

    IF P_PERSONAS%ISOPEN THEN
        LOOP
            FETCH P_PERSONAS
             INTO V_ID_PERSONA,
                  V_NOMBRE,
                  V_APELLIDO,
                  V_EDAD,
                  V_EMAIL,
                  V_FECHA_NACIMIENTO,
                  V_ACTIVO,
                  V_FECHA_REGISTRO;

            EXIT WHEN P_PERSONAS%NOTFOUND;

            P_TOTAL := P_TOTAL + 1;
        END LOOP;
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_CURSOR_IN_WITH_OUTPUTS
(
    P_ENTRADA  IN SYS_REFCURSOR,
    P_TOTAL    OUT NUMBER,
    P_PERSONAS OUT SYS_REFCURSOR
)
AS
    V_ID_PERSONA       NUMBER;
    V_NOMBRE           VARCHAR2(100);
    V_APELLIDO         VARCHAR2(100);
    V_EDAD             NUMBER;
    V_EMAIL            VARCHAR2(150);
    V_FECHA_NACIMIENTO DATE;
    V_ACTIVO           NUMBER;
    V_FECHA_REGISTRO   TIMESTAMP;
BEGIN
    P_TOTAL := 0;

    IF P_ENTRADA%ISOPEN THEN
        LOOP
            FETCH P_ENTRADA
             INTO V_ID_PERSONA,
                  V_NOMBRE,
                  V_APELLIDO,
                  V_EDAD,
                  V_EMAIL,
                  V_FECHA_NACIMIENTO,
                  V_ACTIVO,
                  V_FECHA_REGISTRO;

            EXIT WHEN P_ENTRADA%NOTFOUND;

            P_TOTAL := P_TOTAL + 1;
        END LOOP;
    END IF;

    OPEN P_PERSONAS FOR
        SELECT P.ID_PERSONA,
               P.NOMBRE,
               P.APELLIDO,
               P.EDAD,
               P.EMAIL,
               P.FECHA_NACIMIENTO,
               P.ACTIVO,
               P.FECHA_REGISTRO
          FROM GS_PERSONA P
         ORDER BY P.ID_PERSONA;
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_GET_TWO_CURSORS
(
    P_PERSONAS OUT SYS_REFCURSOR,
    P_HIJOS    OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_PERSONAS FOR
        SELECT P.ID_PERSONA,
               P.NOMBRE,
               P.APELLIDO,
               P.EDAD,
               P.EMAIL,
               P.FECHA_NACIMIENTO,
               P.ACTIVO,
               P.FECHA_REGISTRO
          FROM GS_PERSONA P
         ORDER BY P.ID_PERSONA;

    OPEN P_HIJOS FOR
        SELECT H.ID_HIJO,
               H.ID_PERSONA,
               H.NOMBRE,
               H.APELLIDO,
               H.FECHA_NACIMIENTO
          FROM GS_HIJO H
         ORDER BY H.ID_HIJO;
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_GET_THREE_CURSORS
(
    P_PERSONAS    OUT SYS_REFCURSOR,
    P_HIJOS       OUT SYS_REFCURSOR,
    P_DIRECCIONES OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_PERSONAS FOR
        SELECT P.ID_PERSONA,
               P.NOMBRE,
               P.APELLIDO,
               P.EDAD,
               P.EMAIL,
               P.FECHA_NACIMIENTO,
               P.ACTIVO,
               P.FECHA_REGISTRO
          FROM GS_PERSONA P
         ORDER BY P.ID_PERSONA;

    OPEN P_HIJOS FOR
        SELECT H.ID_HIJO,
               H.ID_PERSONA,
               H.NOMBRE,
               H.APELLIDO,
               H.FECHA_NACIMIENTO
          FROM GS_HIJO H
         ORDER BY H.ID_HIJO;

    OPEN P_DIRECCIONES FOR
        SELECT 'PERSONA' AS TIPO,
               D.ID_PERSONA AS ID_REFERENCIA,
               D.PAIS,
               D.CIUDAD,
               D.TELEFONO
          FROM GS_PERSONA_DIRECCION D
        UNION ALL
        SELECT 'HIJO' AS TIPO,
               HD.ID_HIJO AS ID_REFERENCIA,
               HD.PAIS,
               HD.CIUDAD,
               HD.TELEFONO
          FROM GS_HIJO_DIRECCION HD
         ORDER BY TIPO,
                  ID_REFERENCIA;
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_CURSOR_INOUT_PERSONAS
(
    P_PERSONAS IN OUT SYS_REFCURSOR,
    P_TOTAL    OUT NUMBER
)
AS
    V_ID_PERSONA       NUMBER;
    V_NOMBRE           VARCHAR2(100);
    V_APELLIDO         VARCHAR2(100);
    V_EDAD             NUMBER;
    V_EMAIL            VARCHAR2(150);
    V_FECHA_NACIMIENTO DATE;
    V_ACTIVO           NUMBER;
    V_FECHA_REGISTRO   TIMESTAMP;
BEGIN
    P_TOTAL := 0;

    IF P_PERSONAS%ISOPEN THEN
        LOOP
            FETCH P_PERSONAS
             INTO V_ID_PERSONA,
                  V_NOMBRE,
                  V_APELLIDO,
                  V_EDAD,
                  V_EMAIL,
                  V_FECHA_NACIMIENTO,
                  V_ACTIVO,
                  V_FECHA_REGISTRO;

            EXIT WHEN P_PERSONAS%NOTFOUND;

            P_TOTAL := P_TOTAL + 1;
        END LOOP;

        CLOSE P_PERSONAS;
    END IF;

    OPEN P_PERSONAS FOR
        SELECT P.ID_PERSONA,
               P.NOMBRE,
               P.APELLIDO,
               P.EDAD,
               P.EMAIL,
               P.FECHA_NACIMIENTO,
               P.ACTIVO,
               P.FECHA_REGISTRO
          FROM GS_PERSONA P
         WHERE P.ACTIVO = 1
         ORDER BY P.ID_PERSONA;
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_CURSOR_OUT_NO_METADATA
(
    P_ABRIR_CURSOR IN NUMBER DEFAULT 0,
    P_PERSONAS     OUT SYS_REFCURSOR,
    P_TOTAL        OUT NUMBER,
    P_MENSAJE      OUT VARCHAR2
)
AS
BEGIN
    P_TOTAL := 0;

    IF NVL(P_ABRIR_CURSOR, -1) = 10 THEN
        OPEN P_PERSONAS FOR
            SELECT P.ID_PERSONA,
                   P.NOMBRE,
                   P.APELLIDO,
                   P.EDAD,
                   P.EMAIL,
                   P.FECHA_NACIMIENTO,
                   P.ACTIVO,
                   P.FECHA_REGISTRO
              FROM GS_PERSONA P
             ORDER BY P.ID_PERSONA;

        SELECT COUNT(1)
          INTO P_TOTAL
          FROM GS_PERSONA;

        P_MENSAJE := 'Cursor abierto';
    ELSE
        P_PERSONAS := NULL;
        P_MENSAJE := 'Cursor no abierto para probar metadata no detectable';
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_TYPE_PARAMS
(
    P_ID_PERSONA     IN GS_PERSONA.ID_PERSONA%TYPE,
    P_NOMBRE         OUT GS_PERSONA.NOMBRE%TYPE,
    P_EMAIL          OUT GS_PERSONA.EMAIL%TYPE,
    P_ACTIVO         OUT GS_PERSONA.ACTIVO%TYPE,
    P_FECHA_NACIMIENTO OUT GS_PERSONA.FECHA_NACIMIENTO%TYPE,
    P_FECHA_REGISTRO OUT GS_PERSONA.FECHA_REGISTRO%TYPE
)
AS
BEGIN
    SELECT P.NOMBRE,
           P.EMAIL,
           P.ACTIVO,
           P.FECHA_NACIMIENTO,
           P.FECHA_REGISTRO
      INTO P_NOMBRE,
           P_EMAIL,
           P_ACTIVO,
           P_FECHA_NACIMIENTO,
           P_FECHA_REGISTRO
      FROM GS_PERSONA P
     WHERE P.ID_PERSONA = P_ID_PERSONA;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_NOMBRE := NULL;
        P_EMAIL := NULL;
        P_ACTIVO := NULL;
        P_FECHA_NACIMIENTO := NULL;
        P_FECHA_REGISTRO := NULL;
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_ARRAYS_PRIMITIVOS_OUT
(
    P_NUMEROS    OUT GS_NUMBER_TAB,
    P_ENTEROS    OUT GS_INTEGER_TAB,
    P_BOOLEANOS  OUT GS_BOOLEAN_TAB,
    P_TEXTOS     OUT GS_VARCHAR2_TAB,
    P_FECHAS     OUT GS_DATE_TAB,
    P_TIMESTAMPS OUT GS_TIMESTAMP_TAB
)
AS
BEGIN
    P_NUMEROS := GS_NUMBER_TAB(1, 2, 3, 4, 5);
    P_ENTEROS := GS_INTEGER_TAB(10, 20, 30, 40, 50);
    P_BOOLEANOS := GS_BOOLEAN_TAB(1, 0, 1, 0);
    P_TEXTOS := GS_VARCHAR2_TAB('UNO', 'DOS', 'TRES');
    P_FECHAS := GS_DATE_TAB(DATE '1991-02-18', DATE '2026-08-31');
    P_TIMESTAMPS := GS_TIMESTAMP_TAB
    (
        TIMESTAMP '2026-08-31 10:20:30',
        TIMESTAMP '2026-08-31 00:00:00'
    );
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_ARRAYS_PRIMITIVOS_INOUT
(
    P_NUMEROS    IN GS_NUMBER_TAB,
    P_TEXTOS     IN OUT GS_VARCHAR2_TAB,
    P_FECHAS     OUT GS_DATE_TAB,
    P_TIMESTAMPS OUT GS_TIMESTAMP_TAB,
    P_TOTAL      OUT NUMBER,
    P_SUMA       OUT NUMBER
)
AS
BEGIN
    P_TOTAL := 0;
    P_SUMA := 0;

    IF P_NUMEROS IS NOT NULL THEN
        P_TOTAL := P_TOTAL + P_NUMEROS.COUNT;

        FOR I IN 1 .. P_NUMEROS.COUNT LOOP
            IF P_NUMEROS(I) IS NOT NULL THEN
                P_SUMA := P_SUMA + P_NUMEROS(I);
            END IF;
        END LOOP;
    END IF;

    IF P_TEXTOS IS NULL THEN
        P_TEXTOS := GS_VARCHAR2_TAB();
    END IF;

    P_TOTAL := P_TOTAL + P_TEXTOS.COUNT;
    P_TEXTOS.EXTEND;
    P_TEXTOS(P_TEXTOS.COUNT) := 'AGREGADO_ORACLE';

    P_FECHAS := GS_DATE_TAB(DATE '1991-02-18', TRUNC(SYSDATE));
    P_TIMESTAMPS := GS_TIMESTAMP_TAB
    (
        CAST(SYSTIMESTAMP AS TIMESTAMP),
        TIMESTAMP '1991-02-18 00:00:00'
    );
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_LOB_VALUES
(
    P_TEXTO_IN      IN CLOB,
    P_ARCHIVO_IN    IN BLOB,
    P_TEXTO_OUT     OUT CLOB,
    P_ARCHIVO_OUT   OUT BLOB,
    P_TEXTO_LENGTH  OUT NUMBER,
    P_ARCHIVO_LENGTH OUT NUMBER
)
AS
BEGIN
    IF P_TEXTO_IN IS NULL THEN
        P_TEXTO_LENGTH := 0;
    ELSE
        P_TEXTO_LENGTH := DBMS_LOB.GETLENGTH(P_TEXTO_IN);
    END IF;

    IF P_ARCHIVO_IN IS NULL THEN
        P_ARCHIVO_LENGTH := 0;
    ELSE
        P_ARCHIVO_LENGTH := DBMS_LOB.GETLENGTH(P_ARCHIVO_IN);
    END IF;

    P_TEXTO_OUT := TO_CLOB('Texto CLOB generado desde Oracle');
    P_ARCHIVO_OUT := TO_BLOB(HEXTORAW('486F6C61204F7261636C65'));
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_LOB_INOUT
(
    P_TEXTO          IN OUT CLOB,
    P_ARCHIVO        IN OUT BLOB,
    P_TEXTO_LENGTH   OUT NUMBER,
    P_ARCHIVO_LENGTH OUT NUMBER
)
AS
BEGIN
    IF P_TEXTO IS NULL THEN
        P_TEXTO_LENGTH := 0;
    ELSE
        P_TEXTO_LENGTH := DBMS_LOB.GETLENGTH(P_TEXTO);
    END IF;

    IF P_ARCHIVO IS NULL THEN
        P_ARCHIVO_LENGTH := 0;
    ELSE
        P_ARCHIVO_LENGTH := DBMS_LOB.GETLENGTH(P_ARCHIVO);
    END IF;

    P_TEXTO := TO_CLOB('Texto CLOB actualizado desde Oracle');
    P_ARCHIVO := TO_BLOB(HEXTORAW('424C4F425F41435455414C495A41444F'));
END;
/

CREATE OR REPLACE PROCEDURE GS_SP_LOB_CURSOR
(
    P_LOBS OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_LOBS FOR
        SELECT 1 AS ID_LOB,
               TO_CLOB('Texto CLOB en cursor') AS TEXTO_CLOB,
               TO_BLOB(HEXTORAW('435552534F525F424C4F42')) AS ARCHIVO_BLOB
          FROM DUAL;
END;
/

CREATE OR REPLACE FUNCTION GS_FN_TYPE_NOMBRE
(
    P_ID_PERSONA IN GS_PERSONA.ID_PERSONA%TYPE
)
RETURN GS_PERSONA.NOMBRE%TYPE
AS
    V_NOMBRE GS_PERSONA.NOMBRE%TYPE;
BEGIN
    SELECT P.NOMBRE
      INTO V_NOMBRE
      FROM GS_PERSONA P
     WHERE P.ID_PERSONA = P_ID_PERSONA;

    RETURN V_NOMBRE;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;
/

CREATE OR REPLACE FUNCTION GS_FN_COUNT_PERSONAS
RETURN NUMBER
AS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(1)
      INTO V_TOTAL
      FROM GS_PERSONA;

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION GS_FN_GET_PERSONA_OBJ
(
    P_ID_PERSONA IN NUMBER
)
RETURN GS_PERSONA_OBJ
AS
    V_PERSONA GS_PERSONA_OBJ;
BEGIN
    SELECT GS_PERSONA_OBJ
    (
        P.ID_PERSONA,
        P.NOMBRE,
        P.APELLIDO,
        P.EDAD,
        P.EMAIL,
        P.FECHA_NACIMIENTO,
        P.ACTIVO,
        P.FECHA_REGISTRO
    )
      INTO V_PERSONA
      FROM GS_PERSONA P
     WHERE P.ID_PERSONA = P_ID_PERSONA;

    RETURN V_PERSONA;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;
/

CREATE OR REPLACE FUNCTION GS_FN_GET_PERSONAS_TAB
RETURN GS_PERSONA_TAB
AS
    V_PERSONAS GS_PERSONA_TAB;
BEGIN
    SELECT GS_PERSONA_OBJ
    (
        P.ID_PERSONA,
        P.NOMBRE,
        P.APELLIDO,
        P.EDAD,
        P.EMAIL,
        P.FECHA_NACIMIENTO,
        P.ACTIVO,
        P.FECHA_REGISTRO
    )
      BULK COLLECT INTO V_PERSONAS
      FROM GS_PERSONA P
     ORDER BY P.ID_PERSONA;

    RETURN V_PERSONAS;
END;
/

CREATE OR REPLACE FUNCTION GS_FN_GET_PERSONAS_CURSOR
RETURN SYS_REFCURSOR
AS
    V_PERSONAS SYS_REFCURSOR;
BEGIN
    OPEN V_PERSONAS FOR
        SELECT P.ID_PERSONA,
               P.NOMBRE,
               P.APELLIDO,
               P.EDAD,
               P.EMAIL,
               P.FECHA_NACIMIENTO,
               P.ACTIVO,
               P.FECHA_REGISTRO
          FROM GS_PERSONA P
         ORDER BY P.ID_PERSONA;

    RETURN V_PERSONAS;
END;
/

CREATE OR REPLACE FUNCTION GS_FN_CURSOR_IN_COUNT
(
    P_PERSONAS IN SYS_REFCURSOR
)
RETURN NUMBER
AS
    V_TOTAL            NUMBER := 0;
    V_ID_PERSONA       NUMBER;
    V_NOMBRE           VARCHAR2(100);
    V_APELLIDO         VARCHAR2(100);
    V_EDAD             NUMBER;
    V_EMAIL            VARCHAR2(150);
    V_FECHA_NACIMIENTO DATE;
    V_ACTIVO           NUMBER;
    V_FECHA_REGISTRO   TIMESTAMP;
BEGIN
    IF P_PERSONAS%ISOPEN THEN
        LOOP
            FETCH P_PERSONAS
             INTO V_ID_PERSONA,
                  V_NOMBRE,
                  V_APELLIDO,
                  V_EDAD,
                  V_EMAIL,
                  V_FECHA_NACIMIENTO,
                  V_ACTIVO,
                  V_FECHA_REGISTRO;

            EXIT WHEN P_PERSONAS%NOTFOUND;

            V_TOTAL := V_TOTAL + 1;
        END LOOP;
    END IF;

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION GS_FN_CURSOR_INOUT_PERSONAS
(
    P_PERSONAS IN OUT SYS_REFCURSOR
)
RETURN NUMBER
AS
    V_TOTAL            NUMBER := 0;
    V_ID_PERSONA       NUMBER;
    V_NOMBRE           VARCHAR2(100);
    V_APELLIDO         VARCHAR2(100);
    V_EDAD             NUMBER;
    V_EMAIL            VARCHAR2(150);
    V_FECHA_NACIMIENTO DATE;
    V_ACTIVO           NUMBER;
    V_FECHA_REGISTRO   TIMESTAMP;
BEGIN
    IF P_PERSONAS%ISOPEN THEN
        LOOP
            FETCH P_PERSONAS
             INTO V_ID_PERSONA,
                  V_NOMBRE,
                  V_APELLIDO,
                  V_EDAD,
                  V_EMAIL,
                  V_FECHA_NACIMIENTO,
                  V_ACTIVO,
                  V_FECHA_REGISTRO;

            EXIT WHEN P_PERSONAS%NOTFOUND;

            V_TOTAL := V_TOTAL + 1;
        END LOOP;

        CLOSE P_PERSONAS;
    END IF;

    OPEN P_PERSONAS FOR
        SELECT P.ID_PERSONA,
               P.NOMBRE,
               P.APELLIDO,
               P.EDAD,
               P.EMAIL,
               P.FECHA_NACIMIENTO,
               P.ACTIVO,
               P.FECHA_REGISTRO
          FROM GS_PERSONA P
         WHERE P.ACTIVO = 1
         ORDER BY P.ID_PERSONA;

    RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION GS_FN_CURSOR_RETURN_WITH_OUT
(
    P_ACTIVO IN NUMBER,
    P_TOTAL  OUT NUMBER
)
RETURN SYS_REFCURSOR
AS
    V_PERSONAS SYS_REFCURSOR;
BEGIN
    SELECT COUNT(1)
      INTO P_TOTAL
      FROM GS_PERSONA P
     WHERE P_ACTIVO IS NULL
        OR P.ACTIVO = P_ACTIVO;

    OPEN V_PERSONAS FOR
        SELECT P.ID_PERSONA,
               P.NOMBRE,
               P.APELLIDO,
               P.EDAD,
               P.EMAIL,
               P.FECHA_NACIMIENTO,
               P.ACTIVO,
               P.FECHA_REGISTRO
          FROM GS_PERSONA P
         WHERE P_ACTIVO IS NULL
            OR P.ACTIVO = P_ACTIVO
         ORDER BY P.ID_PERSONA;

    RETURN V_PERSONAS;
END;
/

CREATE OR REPLACE FUNCTION GS_FN_PIPE_PERSONAS
(
    P_ACTIVO IN NUMBER DEFAULT NULL
)
RETURN GS_PERSONA_TAB PIPELINED
AS
BEGIN
    FOR R IN
    (
        SELECT P.ID_PERSONA,
               P.NOMBRE,
               P.APELLIDO,
               P.EDAD,
               P.EMAIL,
               P.FECHA_NACIMIENTO,
               P.ACTIVO,
               P.FECHA_REGISTRO
          FROM GS_PERSONA P
         WHERE P_ACTIVO IS NULL
            OR P.ACTIVO = P_ACTIVO
         ORDER BY P.ID_PERSONA
    )
    LOOP
        PIPE ROW
        (
            GS_PERSONA_OBJ
            (
                R.ID_PERSONA,
                R.NOMBRE,
                R.APELLIDO,
                R.EDAD,
                R.EMAIL,
                R.FECHA_NACIMIENTO,
                R.ACTIVO,
                R.FECHA_REGISTRO
            )
        );
    END LOOP;

    RETURN;
END;
/

CREATE OR REPLACE PACKAGE GS_PKG_TEST AS
    PROCEDURE GET_PERSONA
    (
        P_ID_PERSONA IN NUMBER,
        P_PERSONA    OUT GS_PERSONA_OBJ
    );

    PROCEDURE GET_PERSONAS_CURSOR
    (
        P_PERSONAS OUT SYS_REFCURSOR
    );

    PROCEDURE CURSOR_IN_WITH_OUTPUTS
    (
        P_ENTRADA  IN SYS_REFCURSOR,
        P_TOTAL    OUT NUMBER,
        P_PERSONAS OUT SYS_REFCURSOR
    );

    PROCEDURE ARRAYS_PRIMITIVOS_INOUT
    (
        P_NUMEROS    IN GS_NUMBER_TAB,
        P_TEXTOS     IN OUT GS_VARCHAR2_TAB,
        P_FECHAS     OUT GS_DATE_TAB,
        P_TIMESTAMPS OUT GS_TIMESTAMP_TAB,
        P_TOTAL      OUT NUMBER,
        P_SUMA       OUT NUMBER
    );

    FUNCTION FN_COUNT_PERSONAS RETURN NUMBER;

    FUNCTION FN_GET_PERSONAS_CURSOR RETURN SYS_REFCURSOR;

    FUNCTION PIPE_PERSONAS
    (
        P_ACTIVO IN NUMBER DEFAULT NULL
    )
    RETURN GS_PERSONA_TAB PIPELINED;
END GS_PKG_TEST;
/

CREATE OR REPLACE PACKAGE BODY GS_PKG_TEST AS
    PROCEDURE GET_PERSONA
    (
        P_ID_PERSONA IN NUMBER,
        P_PERSONA    OUT GS_PERSONA_OBJ
    )
    AS
    BEGIN
        GS_SP_GET_PERSONA(P_ID_PERSONA, P_PERSONA);
    END GET_PERSONA;

    PROCEDURE GET_PERSONAS_CURSOR
    (
        P_PERSONAS OUT SYS_REFCURSOR
    )
    AS
    BEGIN
        GS_SP_GET_PERSONAS_CURSOR(P_PERSONAS);
    END GET_PERSONAS_CURSOR;

    PROCEDURE CURSOR_IN_WITH_OUTPUTS
    (
        P_ENTRADA  IN SYS_REFCURSOR,
        P_TOTAL    OUT NUMBER,
        P_PERSONAS OUT SYS_REFCURSOR
    )
    AS
    BEGIN
        GS_SP_CURSOR_IN_WITH_OUTPUTS(P_ENTRADA, P_TOTAL, P_PERSONAS);
    END CURSOR_IN_WITH_OUTPUTS;

    PROCEDURE ARRAYS_PRIMITIVOS_INOUT
    (
        P_NUMEROS    IN GS_NUMBER_TAB,
        P_TEXTOS     IN OUT GS_VARCHAR2_TAB,
        P_FECHAS     OUT GS_DATE_TAB,
        P_TIMESTAMPS OUT GS_TIMESTAMP_TAB,
        P_TOTAL      OUT NUMBER,
        P_SUMA       OUT NUMBER
    )
    AS
    BEGIN
        GS_SP_ARRAYS_PRIMITIVOS_INOUT
        (
            P_NUMEROS,
            P_TEXTOS,
            P_FECHAS,
            P_TIMESTAMPS,
            P_TOTAL,
            P_SUMA
        );
    END ARRAYS_PRIMITIVOS_INOUT;

    FUNCTION FN_COUNT_PERSONAS RETURN NUMBER
    AS
    BEGIN
        RETURN GS_FN_COUNT_PERSONAS();
    END FN_COUNT_PERSONAS;

    FUNCTION FN_GET_PERSONAS_CURSOR RETURN SYS_REFCURSOR
    AS
    BEGIN
        RETURN GS_FN_GET_PERSONAS_CURSOR();
    END FN_GET_PERSONAS_CURSOR;

    FUNCTION PIPE_PERSONAS
    (
        P_ACTIVO IN NUMBER DEFAULT NULL
    )
    RETURN GS_PERSONA_TAB PIPELINED
    AS
    BEGIN
        FOR R IN
        (
            SELECT P.ID_PERSONA,
                   P.NOMBRE,
                   P.APELLIDO,
                   P.EDAD,
                   P.EMAIL,
                   P.FECHA_NACIMIENTO,
                   P.ACTIVO,
                   P.FECHA_REGISTRO
              FROM GS_PERSONA P
             WHERE P_ACTIVO IS NULL
                OR P.ACTIVO = P_ACTIVO
             ORDER BY P.ID_PERSONA
        )
        LOOP
            PIPE ROW
            (
                GS_PERSONA_OBJ
                (
                    R.ID_PERSONA,
                    R.NOMBRE,
                    R.APELLIDO,
                    R.EDAD,
                    R.EMAIL,
                    R.FECHA_NACIMIENTO,
                    R.ACTIVO,
                    R.FECHA_REGISTRO
                )
            );
        END LOOP;

        RETURN;
    END PIPE_PERSONAS;
END GS_PKG_TEST;
/

-- Raw query tests for Generate Service.
-- Copy the SELECT line into the generator. Parameters use :name metadata syntax.

-- GS_Q_PERSONA_BY_NOMBRE
-- SELECT ID_PERSONA, NOMBRE, APELLIDO, EDAD, EMAIL, FECHA_NACIMIENTO, ACTIVO, FECHA_REGISTRO FROM GS_PERSONA WHERE NOMBRE = :nombre;

-- GS_Q_PERSONA_BY_ID
-- SELECT ID_PERSONA, NOMBRE, APELLIDO, EDAD, EMAIL, FECHA_NACIMIENTO, ACTIVO, FECHA_REGISTRO FROM GS_PERSONA WHERE ID_PERSONA = :id_persona;

-- GS_Q_PERSONAS_BY_CITY_JOINSS
-- SELECT P.ID_PERSONA, P.NOMBRE, P.APELLIDO, D.PAIS, D.CIUDAD, D.TELEFONO FROM GS_PERSONA P JOIN GS_PERSONA_DIRECCION D ON D.ID_PERSONA = P.ID_PERSONA WHERE D.CIUDAD = :ciudad;

-- GS_Q_PERSONAS_ACTIVAS_WITH
-- WITH PERSONAS_FILTRADAS AS (SELECT ID_PERSONA, NOMBRE, APELLIDO, ACTIVO FROM GS_PERSONA WHERE ACTIVO = :activo) SELECT ID_PERSONA, NOMBRE, APELLIDO, ACTIVO FROM PERSONAS_FILTRADAS ORDER BY ID_PERSONA;

-- GS_Q_PERSONAS_TOTAL_HIJOS_WITH
-- WITH HIJOS_POR_PERSONA AS (SELECT ID_PERSONA, COUNT(1) AS TOTAL_HIJOS FROM GS_HIJO GROUP BY ID_PERSONA) SELECT P.ID_PERSONA, P.NOMBRE, P.APELLIDO, P.ACTIVO, CAST(NVL(H.TOTAL_HIJOS, 0) AS NUMBER(10)) AS TOTAL_HIJOS FROM GS_PERSONA P LEFT JOIN HIJOS_POR_PERSONA H ON H.ID_PERSONA = P.ID_PERSONA WHERE P.ACTIVO = :activo ORDER BY P.ID_PERSONA;

-- GS_Q_INSERT_PERSONA
-- INSERT INTO GS_PERSONA (NOMBRE, APELLIDO, EDAD, EMAIL, FECHA_NACIMIENTO, ACTIVO) VALUES (:nombre, :apellido, :edad, :email, :fecha_nacimiento, :activo);

-- GS_Q_INSERT_PERSONA_SELECT
-- INSERT INTO GS_PERSONA (NOMBRE, APELLIDO, EDAD, EMAIL, FECHA_NACIMIENTO, ACTIVO) SELECT :nombre, P.APELLIDO, P.EDAD, :email, P.FECHA_NACIMIENTO, :activo FROM GS_PERSONA P WHERE P.ID_PERSONA = :id_persona_base;

-- GS_Q_UPDATE_PERSONASS
-- UPDATE GS_PERSONA SET NOMBRE = :nombre, APELLIDO = :apellido, EDAD = :edad, EMAIL = :email, FECHA_NACIMIENTO = :fecha_nacimiento, ACTIVO = :activo WHERE ID_PERSONA = :id_persona;

-- GS_Q_DELETE_PERSONA
-- DELETE FROM GS_PERSONA WHERE ID_PERSONA = :id_persona;